export { default as Home } from './Home'
export { default as Shop } from './Shop'
export { default as Authentication } from './Authentication'
export { default as Checkout } from './Checkout'
export { default as Category } from './Category'
